### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by suni1mp** [HdrHistogram/HdrHistogram_c#40]
@mikeb01 Hi Mike, I am running wrk with histogram reporting and when i am running @ high TPS(>6000) getting segmentation fault and stack trace states that it crashes in the hdr histogram library.

i have tried with latest histogram, below are the WRK and Histogram repo's i am using

Wrk Repo: https://github.com/yicwang/wrk2.git
HdrHistogram: https://github.com/HdrHistogram/HdrHistogram_c.git

Below is the stack trace and @ahothan pointed me to raise a issue here and i need your help in resolving the issue.

```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/wrk/wrk2/wrk...(no debugging symbols found)...done.
[New LWP 14233]
[New LWP 14216]
[New LWP 14232]
[New LWP 14217]
[New LWP 14226]
[New LWP 14212]
[New LWP 14215]
[New LWP 14230]
[New LWP 14221]
[New LWP 14219]
[New LWP 14225]
[New LWP 14229]
[New LWP 14223]
[New LWP 14228]
[New LWP 14231]
[New LWP 14224]
[New LWP 14227]
[New LWP 14222]
[New LWP 14218]
[New LWP 14213]
[New LWP 14214]
[New LWP 14220]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/wrk/wrk2/wrk -t 20 -c 1000 -d 300 -p 10 -s wrk_script.lua -R 20000 https:/'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f12158c0292 in counts_get_direct () from /usr/local/lib/libhdr_histogram.so.1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f12158c0292 in counts_get_direct () from /usr/local/lib/libhdr_histogram.so.1
#1  0x00007f12158c02c8 in counts_get_normalised () from /usr/local/lib/libhdr_histogram.so.1
#2  0x00007f12158c138e in move_next () from /usr/local/lib/libhdr_histogram.so.1
#3  0x00007f12158c14da in _basic_iter_next () from /usr/local/lib/libhdr_histogram.so.1
#4  0x00007f12158c1962 in _recorded_iter_next () from /usr/local/lib/libhdr_histogram.so.1
#5  0x00007f12158c15f2 in hdr_iter_next () from /usr/local/lib/libhdr_histogram.so.1
#6  0x00007f12158c0e61 in hdr_add () from /usr/local/lib/libhdr_histogram.so.1
#7  0x0000000000408ae5 in gen_stats ()
#8  0x0000000000409106 in period_report_func ()
#9  0x000000000040bde2 in aeProcessEvents ()
#10 0x000000000040c06b in aeMain ()
#11 0x00000000004079fa in period_report ()
#12 0x00007f1216428dc5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f12151d973d in clone () from /lib64/libc.so.6
```

**Comment by mikeb01** [comment]
If you could check out the latest, I've added some additional bounds checking.

**Comment by suni1mp** [comment]
wow thank you @mikeb01 , seems like segmentation issue is resolved, i am still trying few more options, will confirm by tomorrow.

**Comment by suni1mp** [comment]
Thank you @mikeb01 , Mike, this is to confirm that the issue is resolved, i have encountered segmentation fault once today but not able to reproduce the issue.

**Comment by mikeb01** [comment]
Okay, thanks.  If you do encounter any more raise another issue with a backtrace or core file.
