### ISSUE TITLE
hdr_add( ) causes memory corruption?

### ISSUE THREAD

**Issue by neutronsharc** [HdrHistogram/HdrHistogram_c#56]
Hi developers,  I have been using hdr_histogram c version for a while. It's very convenient and powerful.  Thank you for the great work.

Meanwhile I'm concerned with thread safety.  I have several threads adding values to hdr_histogram at the same time, and they appear to work fine without locking.  But I want to confirm with the developers.

I also call hdr_add( ) to merge several hdr_histograms into one.  But this method seems to cause memory overrun and my program crashes. Below is the backtrace produced by address sanitizer. You can see that the hdr_add( ) method call leads to crash.

ASAN:SIGSEGV
=================================================================
==68521==ERROR: AddressSanitizer: SEGV on unknown address 0x626c0157a960 (pc 0x00000169d041 bp 0x7fbb9b281e20 sp 0x7fbb9b281e10 T78)
    #0 0x169d040 in counts_get_direct /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:50
    #1 0x169d0ac in counts_get_normalised /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:55
    #2 0x16a027d in move_next /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:617
    #3 0x16a0783 in _basic_iter_next /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:651
    #4 0x16a13f9 in _recorded_iter_next /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:798
    #5 0x16a0b11 in hdr_iter_next /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:691
    #6 0x169f203 in hdr_add /home/hcd/shawn/code/hstore/daelaam/common/lib/hdr_histogram/src/hdr_histogram.c:436
    #7 0x1683335 in hcd::HcdHistogram::Merge(hcd::HcdHistogram*) /home/hcd/shawn/code/hstore/daelaam/common/lib/hcdcommon/src/hcd_histogram.cpp:152
    #8 0x1334750 in hcd::LatencyBreakdown::Merge(hcd::LatencyBreakdown*) /home/hcd/shawn/code/hstore/daelaam/hcdstruct/src/latency_recorder.cpp:96
    #9 0x1335ea8 in hcd::LatencyRecorder::Merge(hcd::LatencyBreakdown*, hcd::HTaskType) /home/hcd/shawn/code/hstore/daelaam/hcdstruct/src/latency_recorder.cpp:179
    #10 0x133650c in hcd::LatencyRecorder::Merge(hcd::LatencyRecorder*) /home/hcd/shawn/code/hstore/daelaam/hcdstruct/src/latency_recorder.cpp:194
    #11 0xc28592 in hcd::StatsPrinter::PrinterLoop() /home/hcd/shawn/code/hstore/daelaam/threadpool/src/stats_printer.cpp:55
    #12 0xc327f3 in void std::_Mem_fn_base<void (hcd::StatsPrinter::*)(), true>::operator()<, void>(hcd::StatsPrinter*) const /usr/include/c++/5/functional:600
    #13 0xc32682 in void std::_Bind_simple<std::_Mem_fn<void (hcd::StatsPrinter::*)()> (hcd::StatsPrinter*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/5/functional:1531
    #14 0xc323af in std::_Bind_simple<std::_Mem_fn<void (hcd::StatsPrinter::*)()> (hcd::StatsPrinter*)>::operator()() /usr/include/c++/5/functional:1520
    #15 0xc322cd in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (hcd::StatsPrinter::*)()> (hcd::StatsPrinter*)> >::_M_run() /usr/include/c++/5/thread:115
    #16 0x7fbbc93bfc7f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c7f)
    #17 0x7fbbc98926b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #18 0x7fbbc8b2541c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

**Comment by giltene** [comment]
For the first part of the question, relating to recording values to one hdr_histogram from multiple threads without locking or some other synchronization, the implementation provides no thread safety, and these operations certainly not thread safe. Effects of uncoordinated concurrent access to an hdr_histogram are undefined (as in "may include crashes or worse").

For the hdr_add part of the question, is this hdr_add being done in a multithreaded environment with other threads potentially making other calls on the same hdr_histogram with no synchronization? Or was the hdr_histogram recorded to by multiple threads with no synchronization prior to the hdr_add() call? If the answer to either of these is "yes", see answer first part above. Corruption of the hdr_histogram data structure (and e.g. a mismatch between the actual counts and the total_counts field which would directly cause the above-reported crash) can easily happen through concurrent misuse. If "no", please provide snippets showing the calling and recording code.

**Comment by neutronsharc** [comment]
Just FYI,  what I found is,  it's ok to have concurrent hdr_record_value()  and hdr_get_value()  without locking protection.  There will be occasional odd data, but generally ok. 

The corruption happens when hdr_add() happens in parallel with other read/write.

**Comment by mikeb01** [comment]
Please don't rely on this.  It is not tested for and may break in the future.

**Comment by neutronsharc** [comment]
@giltene  @mikeb01  Thanks for the warning!
